# Generated by Django 6.0.3 on 2026-04-06 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
